import torch

from .neurons import SpikingNeuron


__all__ = ["CustomNeuron", "neuron_from_equations"]


class CustomNeuron(SpikingNeuron):
    """
    Base class for a neuron generated by :func:`neuron_from_equations`. Not
    normally instantiated directly -- call :func:`neuron_from_equations` to
    build a subclass from your own state equations, then use the returned
    class exactly like any other snnTorch neuron.
    """

    #: names of the state variables this neuron carries, e.g. ``("mem",)``
    #: or ``("v", "u")``. Set by :func:`neuron_from_equations`.
    state_names: tuple = ()
    #: which state variable is compared against ``threshold`` to fire.
    #: Defaults to ``state_names[0]``.
    spike_state = None
    #: initial value for each state variable (defaults to 0.0).
    init_values: dict = {}
    #: optional ``fn(states, spk, threshold) -> states`` applied after a
    #: firing decision, INSTEAD of ``reset_mechanism``. Use this when a
    #: model's reset doesn't fit "subtract" / "zero" / "none" (e.g.
    #: Izhikevich's `v <- c, u <- u + d`).
    reset_fn = None

    # NOTE on reset timing: when reset_fn is None, `reset_mechanism` is
    # applied to spike_state in the SAME step as the firing decision that
    # triggered it (an "immediate" reset). This is the common textbook
    # convention, and is exactly equivalent to snntorch.Leaky called with
    # `reset_delay=False` -- NOT snntorch.Leaky's own default
    # (`reset_delay=True`), which deliberately applies the subtraction one
    # step later. Verified: CustomNeuron built from Leaky's own update
    # equation matches `Leaky(beta=..., reset_delay=False)` bit-for-bit.

    @staticmethod
    def update_fn(states, input_):
        """``fn(states: dict, input_: Tensor) -> dict``. Must be supplied
        via :func:`neuron_from_equations`; computes every state variable's
        next value from the current states and this step's input."""
        raise NotImplementedError(
            "CustomNeuron.update_fn was not set -- build this neuron with "
            "neuron_from_equations(), not CustomNeuron() directly."
        )

    def __init__(
        self,
        threshold=1.0,
        spike_grad=None,
        surrogate_disable=False,
        init_hidden=False,
        inhibition=False,
        learn_threshold=False,
        reset_mechanism="subtract",
        state_quant=False,
        output=False,
        graded_spikes_factor=1.0,
        learn_graded_spikes_factor=False,
    ):
        if not self.state_names:
            raise TypeError(
                "CustomNeuron subclasses must define state_names; build one "
                "with neuron_from_equations() rather than instantiating "
                "CustomNeuron directly."
            )
        super().__init__(
            threshold,
            spike_grad,
            surrogate_disable,
            init_hidden,
            inhibition,
            learn_threshold,
            reset_mechanism,
            state_quant,
            output,
            graded_spikes_factor,
            learn_graded_spikes_factor,
        )
        if self.spike_state is None:
            self.spike_state = self.state_names[0]
        elif self.spike_state not in self.state_names:
            raise ValueError(
                f"spike_state '{self.spike_state}' is not one of "
                f"state_names {self.state_names}."
            )
        for name in self.state_names:
            self.register_buffer(name, torch.zeros(0), persistent=False)

    # ------------------------------------------------------------------ #
    #  state management -- mirrors Leaky.init_leaky()/reset_mem()
    # ------------------------------------------------------------------ #
    def _lazy_init(self, input_):
        for name in self.state_names:
            cur = getattr(self, name)
            if cur.shape != input_.shape:
                val = float(self.init_values.get(name, 0.0))
                setattr(
                    self,
                    name,
                    torch.full_like(input_, val, device=input_.device),
                )

    def reset_state(self):
        """Zero every state variable. Call once per sequence."""
        for name in self.state_names:
            setattr(self, name, torch.zeros_like(getattr(self, name)))
        return tuple(getattr(self, name) for name in self.state_names)

    # ------------------------------------------------------------------ #
    #  forward
    # ------------------------------------------------------------------ #
    def forward(self, input_, *states):
        if states:
            if self.init_hidden:
                raise TypeError(
                    "state tensors should not be passed as arguments while "
                    "init_hidden=True"
                )
            if len(states) != len(self.state_names):
                raise TypeError(
                    f"expected {len(self.state_names)} state tensor(s) "
                    f"{self.state_names}, got {len(states)}."
                )
            for name, s in zip(self.state_names, states):
                setattr(self, name, s)

        self._lazy_init(input_)

        cur = {name: getattr(self, name) for name in self.state_names}
        nxt = dict(self.update_fn(cur, input_))
        missing = set(self.state_names) - set(nxt)
        if missing:
            raise ValueError(
                f"update_fn did not return a value for: {sorted(missing)}"
            )

        spk_val = nxt[self.spike_state]
        if self.state_quant:
            spk_val = self.state_quant(spk_val)

        if self.inhibition:
            spk = self.fire_inhibition(spk_val.size(0), spk_val)
        else:
            spk = self.fire(spk_val)

        if self.reset_fn is not None:
            nxt = dict(self.reset_fn(nxt, spk, self.threshold))
        elif self.reset_mechanism_val == 0:  # subtract
            nxt[self.spike_state] = (
                nxt[self.spike_state] - spk.detach() * self.threshold
            )
        elif self.reset_mechanism_val == 1:  # zero
            nxt[self.spike_state] = (1 - spk.detach()) * nxt[self.spike_state]
        # == 2 ("none"): no reset

        for name in self.state_names:
            setattr(self, name, nxt[name])

        out_states = tuple(nxt[name] for name in self.state_names)
        if self.output:
            return (spk,) + out_states
        elif self.init_hidden:
            return spk
        else:
            return (spk,) + out_states


def neuron_from_equations(
    name, state_names, update_fn, spike_state=None, reset_fn=None,
    init_values=None,
):
    """
    Generate a new spiking-neuron **class** from user-supplied state
    equations. The returned class is used exactly like any other snnTorch
    neuron -- ``init_hidden``, ``output``, ``threshold``, ``spike_grad``,
    ``reset_mechanism``, etc. all work.

    Example -- a two-state Izhikevich-style neuron::

        import snntorch as snn

        def izh_update(states, I):
            v, u = states["v"], states["u"]
            dv = 0.04 * v ** 2 + 5 * v + 140 - u + I
            du = 0.02 * (0.2 * v - u)
            return {"v": v + dv, "u": u + du}

        def izh_reset(states, spk, threshold):
            v, u = states["v"], states["u"]
            fired = spk.detach().bool()
            v = torch.where(fired, torch.full_like(v, -65.0), v)
            u = torch.where(fired, u + 8.0, u)
            return {"v": v, "u": u}

        Izhikevich = snn.neuron_from_equations(
            "Izhikevich", state_names=("v", "u"), update_fn=izh_update,
            spike_state="v", reset_fn=izh_reset, init_values={"v": -65.0},
        )

        lif = Izhikevich(threshold=30.0)
        spk, (v, u) = lif(I), None  # first call auto-initialises state
        # or, matching every other neuron's calling convention:
        spk, v, u = lif(I)

    :param name: class name for the generated neuron (used for
        ``type.__name__`` / ``repr``; purely cosmetic).
    :type name: str

    :param state_names: names of the state variables to carry between
        steps, e.g. ``("mem",)`` or ``("v", "u")``.
    :type state_names: tuple of str

    :param update_fn: ``fn(states: dict[str, Tensor], input_: Tensor) ->
        dict[str, Tensor]``. Computes every state's next value from the
        current states and this step's input. Must return a value for
        every name in ``state_names``.
    :type update_fn: callable

    :param spike_state: which state variable is compared against
        ``threshold`` to decide whether the neuron fires. Defaults to
        ``state_names[0]``.
    :type spike_state: str, optional

    :param reset_fn: ``fn(states, spk, threshold) -> states``, applied
        after the firing decision, in place of the standard
        ``reset_mechanism``. Use this when the model's reset rule isn't a
        plain subtract/zero of ``spike_state`` (e.g. Izhikevich's
        ``v <- c, u <- u + d``). If ``None`` (default), the usual
        ``reset_mechanism`` ("subtract" / "zero" / "none") is applied to
        ``spike_state``, exactly as :class:`snntorch.Leaky` does to
        ``mem``.
    :type reset_fn: callable, optional

    :param init_values: initial value for each state variable (default
        0.0 for any not listed). Applied the first time the neuron is
        called, or after :meth:`CustomNeuron.reset_state`.
    :type init_values: dict, optional

    :return: a new subclass of :class:`CustomNeuron`, ready to instantiate
        with the standard :class:`SpikingNeuron` keyword arguments
        (``threshold``, ``spike_grad``, ``init_hidden``, ``output``,
        ``reset_mechanism``, ``inhibition``, ``state_quant``,
        ``graded_spikes_factor``, ...).
    :rtype: type
    """
    if spike_state is None:
        spike_state = state_names[0]
    attrs = {
        "state_names": tuple(state_names),
        "spike_state": spike_state,
        "update_fn": staticmethod(update_fn),
        "init_values": dict(init_values or {}),
    }
    if reset_fn is not None:
        attrs["reset_fn"] = staticmethod(reset_fn)
    return type(name, (CustomNeuron,), attrs)
