# This workflow will upload a Python package using Twine when a tag is created and all tests run successfully
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python package

on:
  workflow_run: 
    workflows: ["snnTorch CD"]
    # branches: [main] 
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
